const KEY='jarvis_functional_preview_v1';
const todayISO=()=>{const d=new Date(),tz=d.getTimezoneOffset()*60000;return new Date(d-tz).toISOString().slice(0,10)};
const defaults={name:'Jan',city:'Wittlich',links:[{title:'ChatGPT',url:'https://chatgpt.com'},{title:'GitHub',url:'https://github.com'},{title:'Kalender',url:'https://calendar.google.com'},{title:'E-Mail',url:'https://mail.google.com'},{title:'Drive',url:'https://drive.google.com'}],events:[],tasks:[],projects:[
{name:'KISS',state:'Aktiv',next:'Nächsten Gründungsschritt und Angebotsstruktur festlegen.',url:'',repo:''},
{name:'Weinkommission Porn',state:'Design',next:'Hero und Seitenstruktur auf Premium-Niveau weiterführen.',url:'',repo:''},
{name:'wunschausbau2',state:'Build',next:'Website stabilisieren und Backend-Konzept vorbereiten.',url:'',repo:''},
{name:'Reitanlage Eichhorn',state:'Review',next:'Repo-Status prüfen und offene Website-Punkte priorisieren.',url:'',repo:''},
{name:'Dashboard',state:'Build',next:'Heute-Seite weiter auf echte Entscheidungshilfe trimmen.',url:'https://hapo3005.github.io/dash/',repo:'https://github.com/hapo3005/dash'}]};
function load(){try{const raw=JSON.parse(localStorage.getItem(KEY)||'{}');return {...structuredClone(defaults),...raw,projects:raw.projects||structuredClone(defaults.projects),links:raw.links||structuredClone(defaults.links),tasks:raw.tasks||[],events:raw.events||[]}}catch{return structuredClone(defaults)}}
let data=load();
const save=()=>localStorage.setItem(KEY,JSON.stringify(data));
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const prioScore={high:0,medium:1,low:2};
function openTasks(){return (data.tasks||[]).filter(t=>!t.done)}
function todayTasks(){return openTasks().filter(t=>!t.due||t.due===todayISO())}
function rankedTasks(){return todayTasks().slice().sort((a,b)=>(prioScore[a.priority]??9)-(prioScore[b.priority]??9)||(a.minutes??999)-(b.minutes??999))}
function nextEvents(){return (data.events||[]).slice().sort((a,b)=>(a.time||'99:99').localeCompare(b.time||'99:99'))}
function minutesUntil(time){if(!/^\d{1,2}:\d{2}$/.test(time||''))return null;const [h,m]=time.split(':').map(Number),now=new Date(),then=new Date();then.setHours(h,m,0,0);return Math.round((then-now)/60000)}
function recommendation(){const tasks=rankedTasks(),next=nextEvents()[0],free=next?minutesUntil(next.time):null;if(!tasks.length)return {title:'Keine dringende Aufgabe offen',copy:next?`Nutze die freie Zeit bewusst. Nächster Termin: ${next.time} · ${next.title}.`:'Heute gibt es aktuell keinen priorisierten Arbeitsblock.'};let candidates=tasks;if(free!==null&&free>0)candidates=tasks.filter(t=>(t.minutes||30)<=Math.max(10,free-10));const t=candidates[0]||tasks[0];let copy=`Plane dafür etwa ${t.minutes||30} Minuten ein.`;if(next&&free!==null&&free>0)copy+=` Bis ${next.time} sind noch ca. ${free} Minuten frei.`;if(next&&free!==null&&free<=15)copy=`Der nächste Termin ist bereits um ${next.time}. Starte vorher keinen großen neuen Block.`;return {title:t.title,copy}}
function renderHeader(){const now=new Date();$('clock').textContent=now.toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'});$('date').textContent=now.toLocaleDateString('de-DE',{weekday:'short',day:'2-digit',month:'2-digit'});const h=now.getHours();$('hello').textContent=`${h<11?'Guten Morgen':h<17?'Guten Tag':'Guten Abend'}, ${data.name||'Jan'}.`}
function renderToday(){const top=rankedTasks().slice(0,3),rec=recommendation(),evs=nextEvents().slice(0,3);$('todayFocus').innerHTML=top.length?top.map((t,i)=>`<div class="focus-item"><div class="focus-rank">${i+1}</div><div><div class="title">${esc(t.title)}</div><div class="meta">${esc(t.project||'Ohne Projekt')} · ${t.minutes||30} Min.</div></div><span class="badge ${esc(t.priority||'medium')}">${t.priority==='high'?'Hoch':t.priority==='low'?'Niedrig':'Mittel'}</span></div>`).join(''):'<div class="empty">Für heute ist noch nichts priorisiert.</div>';$('nowTitle').textContent=rec.title;$('nowCopy').textContent=rec.copy;$('todayEvents').innerHTML=evs.length?evs.map(e=>`<div class="event"><div class="time">${esc(e.time||'--:--')}</div><div><div class="title">${esc(e.title)}</div><div class="meta">${esc(e.note||'')}</div></div></div>`).join(''):'<div class="empty">Keine Termine eingetragen.</div>';$('todayProjects').innerHTML=(data.projects||[]).slice(0,4).map(p=>`<div class="event"><div><div class="title">${esc(p.name)}</div><div class="meta">${esc(p.next||'Kein nächster Schritt hinterlegt.')}</div></div></div>`).join('');$('quicklinks').innerHTML=(data.links||[]).slice(0,6).map(l=>`<a href="${esc(l.url)}" target="_blank" rel="noopener">${esc(l.title)}</a>`).join('')}
function renderProjects(){$('projectList').innerHTML=(data.projects||[]).map(p=>`<div class="project"><div class="project-head"><div class="title">${esc(p.name)}</div><div class="project-state">${esc(p.state||'Aktiv')}</div></div><div class="project-next"><span class="subtle">Nächster Schritt</span><div style="margin-top:5px">${esc(p.next||'Noch nicht definiert.')}</div></div><div class="project-links">${p.url?`<a href="${esc(p.url)}" target="_blank">Live</a>`:''}${p.repo?`<a href="${esc(p.repo)}" target="_blank">Repo</a>`:''}</div></div>`).join('')}
function renderTasks(){const list=(data.tasks||[]).slice().sort((a,b)=>Number(a.done)-Number(b.done)||(prioScore[a.priority]??9)-(prioScore[b.priority]??9));$('taskList').innerHTML=list.length?list.map(t=>`<div class="task ${t.done?'done':''}" data-id="${esc(t.id)}"><button class="check" data-act="toggle">${t.done?'✓':''}</button><div><div class="title">${esc(t.title)}</div><div class="meta">${esc(t.project||'Ohne Projekt')} · ${t.minutes||30} Min. · ${t.area==='private'?'Privat':'Geschäftlich'}</div></div><div class="task-actions"><button class="iconbtn" data-act="delete">Löschen</button></div></div>`).join(''):'<div class="empty">Noch keine Aufgaben vorhanden.</div>'}
function renderCalendar(){$('calendarEvents').innerHTML=nextEvents().length?nextEvents().map(e=>`<div class="event" data-id="${esc(e.id)}"><div class="time">${esc(e.time)}</div><div style="flex:1"><div class="title">${esc(e.title)}</div><div class="meta">${esc(e.note||'')}</div></div><button class="iconbtn" data-event-delete="${esc(e.id)}">Löschen</button></div>`).join(''):'<div class="empty">Keine Termine eingetragen.</div>'}
function renderModules(){$('moduleList').innerHTML=`<div class="module"><div class="title">Gesundheit</div><p>Bewusst aus der Startseite entfernt. Hier kann später Xiaomi/Health angebunden werden und nur bei echtem Handlungsbedarf auf „Heute“ erscheinen.</p></div><div class="module"><div class="title">Smart Home</div><p>Hausmodi, Licht und Automationen bleiben ein separates Modul statt permanente Ablenkung.</p></div><div class="module"><div class="title">Finanzen</div><p>Später: Kontostand, Budgets, wiederkehrende Kosten und auffällige Abweichungen – nicht jeder Einzelwert.</p></div><div class="module"><div class="title">Weitere Projekte</div><p>Immobilien, Einkauf, Mobilität und andere Themen können hier modular angebunden werden.</p></div>`}
function renderAll(){renderHeader();renderToday();renderProjects();renderTasks();renderCalendar();renderModules();$('projectOptions').innerHTML='<option value="">Ohne Projekt</option>'+(data.projects||[]).map(p=>`<option>${esc(p.name)}</option>`).join('')}
function showPage(page){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===`page-${page}`));document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));location.hash=page}
async function weather(){try{const city=data.city||'Wittlich',g=await fetch(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(city)}&count=1&language=de&format=json`).then(r=>r.json()),p=g.results?.[0];if(!p)return;const w=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${p.latitude}&longitude=${p.longitude}&current=temperature_2m,weather_code&timezone=auto`).then(r=>r.json());$('weather').textContent=`${Math.round(w.current.temperature_2m)}° · ${p.name}`}catch{$('weather').textContent='Wetter offline'}}
document.addEventListener('click',e=>{const nav=e.target.closest('[data-page]');if(nav){showPage(nav.dataset.page);return}const t=e.target.closest('.task');if(t&&e.target.dataset.act){const x=data.tasks.find(a=>a.id===t.dataset.id);if(!x)return;if(e.target.dataset.act==='toggle')x.done=!x.done;if(e.target.dataset.act==='delete')data.tasks=data.tasks.filter(a=>a.id!==x.id);save();renderAll();return}if(e.target.dataset.eventDelete){data.events=data.events.filter(x=>x.id!==e.target.dataset.eventDelete);save();renderAll();return}if(e.target.id==='whatNow'){const rec=recommendation();$('nowTitle').textContent=rec.title;$('nowCopy').textContent=rec.copy;$('nowBox').scrollIntoView({behavior:'smooth',block:'center'})}});
$('taskForm').addEventListener('submit',e=>{e.preventDefault();const title=$('taskTitle').value.trim();if(!title)return;data.tasks.unshift({id:crypto.randomUUID(),title,project:$('projectOptions').value,priority:$('taskPriority').value,area:$('taskArea').value,minutes:Number($('taskMinutes').value)||30,due:todayISO(),done:false,created:new Date().toISOString()});save();e.target.reset();$('taskMinutes').value=30;renderAll()});
$('eventForm').addEventListener('submit',e=>{e.preventDefault();const title=$('eventTitle').value.trim(),time=$('eventTime').value.trim();if(!title||!time)return;data.events.push({id:crypto.randomUUID(),title,time,note:$('eventNote').value.trim()});save();e.target.reset();renderAll()});
window.addEventListener('hashchange',()=>showPage((location.hash||'#today').slice(1)));renderAll();showPage((location.hash||'#today').slice(1));weather();setInterval(renderHeader,30000);