const KEY='jarvis_functional_preview_v1';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const uid=()=>crypto.randomUUID();
const todayISO=()=>{const d=new Date(),tz=d.getTimezoneOffset()*60000;return new Date(d-tz).toISOString().slice(0,10)};
const projectDefaults=[
 {name:'KISS',state:'Aufbau',goal:'Markteintritt vorbereiten und erste zahlende Kunden gewinnen.',milestone:'Leistungsangebot und Positionierung finalisieren.',next:'Leistungsumfang und Einstiegspreise endgültig festlegen.',blocker:'Referenzen müssen noch systematisch aufgebaut werden.',last:'Preisstrategie für die Region angepasst.',url:'',repo:''},
 {name:'Weinkommission Porn',state:'Design',goal:'Premium-Webpräsenz für eine führende Weinkommission an der Mosel entwickeln.',milestone:'Visuelle Richtung und Hero finalisieren.',next:'Hero und Seitenstruktur auf Premium-Niveau weiterführen.',blocker:'Finale Marken-/Logoentscheidung noch offen.',last:'Mehrere Premium-Richtungen für Website und Logo entwickelt.',url:'',repo:''},
 {name:'wunschausbau2',state:'Build',goal:'Professionelle Website als belastbare Vertriebs- und Referenzplattform aufbauen.',milestone:'Frontend stabilisieren und Backend-Richtung festlegen.',next:'Website stabilisieren und Backend-Konzept vorbereiten.',blocker:'Backend-Umfang noch nicht endgültig entschieden.',last:'Aktuellen Stand als Hauptprojekt bestätigt.',url:'',repo:''},
 {name:'Reitanlage Eichhorn',state:'Review',goal:'Webauftritt technisch und gestalterisch sauber abschließen.',milestone:'Repo und offene Website-Punkte bereinigen.',next:'Repo-Status prüfen und offene Punkte priorisieren.',blocker:'Aktueller Repo-Stand muss regelmäßig verifiziert werden.',last:'Projekt wieder in die aktive Prüfung aufgenommen.',url:'',repo:''},
 {name:'Dashboard',state:'Build',goal:'Ein persönliches Operating System schaffen, das täglich Zeit und Entscheidungen spart.',milestone:'V4 als professionelle Arbeitszentrale etablieren.',next:'V4 im echten Alltag testen und nur nützliche Signale weiter ausbauen.',blocker:'Echte Kalender- und GitHub-Daten sind noch nicht automatisch angebunden.',last:'Informationsarchitektur auf Personal OS umgestellt.',url:'https://hapo3005.github.io/dash/',repo:'https://github.com/hapo3005/dash'}
];
const defaults={name:'Jan',city:'Wittlich',links:[{title:'ChatGPT',url:'https://chatgpt.com'},{title:'GitHub',url:'https://github.com'},{title:'Kalender',url:'https://calendar.google.com'},{title:'E-Mail',url:'https://mail.google.com'},{title:'Drive',url:'https://drive.google.com'}],events:[],tasks:[],inbox:[],projects:projectDefaults};
function load(){try{const raw=JSON.parse(localStorage.getItem(KEY)||'{}');const merged={...structuredClone(defaults),...raw};merged.projects=(raw.projects?.length?raw.projects:structuredClone(projectDefaults)).map((p,i)=>({...projectDefaults.find(x=>x.name===p.name),...p,id:p.id||`project-${i}`}));merged.tasks=(raw.tasks||[]).map(t=>({...t,id:t.id||uid(),bucket:t.bucket||(t.done?'done':'today'),note:t.note||''}));merged.events=(raw.events||[]).map(e=>({...e,id:e.id||uid(),duration:Number(e.duration)||60}));merged.inbox=raw.inbox||[];merged.links=raw.links||structuredClone(defaults.links);return merged}catch{return structuredClone(defaults)}}
let data=load();let activeQueue='today';let context=null;let currentNowTaskId=null;
const save=()=>localStorage.setItem(KEY,JSON.stringify(data));
const prioScore={high:0,medium:1,low:2};
const labelPriority=p=>p==='high'?'Hoch':p==='low'?'Niedrig':'Mittel';
function openTasks(){return data.tasks.filter(t=>!t.done)}
function rankedTasks(bucket='today'){return openTasks().filter(t=>(t.bucket||'today')===bucket).sort((a,b)=>(prioScore[a.priority]??9)-(prioScore[b.priority]??9)||(a.minutes??999)-(b.minutes??999))}
function timeToMinutes(time){if(!/^\d{1,2}:\d{2}$/.test(time||''))return null;const [h,m]=time.split(':').map(Number);return h*60+m}
function nowMinutes(){const n=new Date();return n.getHours()*60+n.getMinutes()}
function futureEvents(){const n=nowMinutes();return data.events.slice().filter(e=>timeToMinutes(e.time)!==null&&timeToMinutes(e.time)>=n).sort((a,b)=>a.time.localeCompare(b.time))}
function allEvents(){return data.events.slice().sort((a,b)=>(a.time||'99:99').localeCompare(b.time||'99:99'))}
function currentFreeMinutes(){const next=futureEvents()[0];if(!next)return 180;return Math.max(0,timeToMinutes(next.time)-nowMinutes())}
function recommendation(){const tasks=rankedTasks('today');const next=futureEvents()[0];const free=currentFreeMinutes();if(!tasks.length)return {task:null,title:'Kein Arbeitsblock priorisiert',copy:next?`Bis ${next.time} ist aktuell kein konkreter Arbeitsblock geplant.`:'Für heute ist keine Aufgabe priorisiert. Nutze die freie Kapazität bewusst.',free,next};if(next&&free<=15)return {task:null,title:`Termin um ${next.time} vorbereiten`,copy:`Bis ${next.title} sind nur noch etwa ${free} Minuten. Starte keinen neuen größeren Block.`,free,next};const usable=Math.max(10,free-10);const fits=tasks.filter(t=>(Number(t.minutes)||30)<=usable);const task=fits[0]||tasks[0];return {task,title:task.title,copy:next?`${task.project?task.project+' · ':''}${task.minutes||30} Min. Passt in das freie Fenster vor ${next.time}.`:`${task.project?task.project+' · ':''}${task.minutes||30} Min. Kein Termin begrenzt den aktuellen Arbeitsblock.`,free,next}}
function showPage(page){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===`page-${page}`));document.querySelectorAll('.side-nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));$('crumb').textContent=({today:'Heute',inbox:'Inbox',projects:'Projekte',tasks:'Work Queue',calendar:'Kalender',monitor:'Monitor',library:'Library',modules:'Module'})[page]||'Personal OS';location.hash=page;document.querySelector('.sidebar').classList.remove('open')}
function renderHeader(){const n=new Date(),h=n.getHours();$('clock').textContent=n.toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'});$('date').textContent=n.toLocaleDateString('de-DE',{weekday:'long',day:'2-digit',month:'long'});$('hello').textContent=`${h<11?'Guten Morgen':h<17?'Guten Tag':'Guten Abend'}, ${data.name||'Jan'}.`}
function renderSignals(){const signals=[];const next=futureEvents()[0];if(next)signals.push(`<span class="signal">Nächster Termin ${esc(next.time)} · ${esc(next.title)}</span>`);signals.push(`<span class="signal">${rankedTasks('today').length} Aufgaben heute</span>`);if(data.inbox.length)signals.push(`<span class="signal attention">${data.inbox.length} ungeklärte Inbox-Einträge</span>`);const blockers=data.projects.filter(p=>p.blocker&&p.blocker!=='—').length;if(blockers)signals.push(`<span class="signal">${blockers} Projektblocker dokumentiert</span>`);$('signalStrip').innerHTML=signals.join('')}
function renderToday(){renderSignals();const rec=recommendation();currentNowTaskId=rec.task?.id||null;$('nowTitle').textContent=rec.title;$('nowCopy').textContent=rec.copy;$('startNow').disabled=!rec.task;$('deferNow').disabled=!rec.task;$('openNowProject').disabled=!rec.task?.project;$('nowMeta').innerHTML=rec.task?`<span>Priorität: ${labelPriority(rec.task.priority)}</span><span>Dauer: ${rec.task.minutes||30} Min.</span><span>Projekt: ${esc(rec.task.project||'Ohne Projekt')}</span>${rec.next?`<span>Nächster Termin: ${esc(rec.next.time)}</span>`:''}`:'';const after=rankedTasks('today').filter(t=>t.id!==currentNowTaskId).slice(0,3);$('todayFocus').innerHTML=after.length?after.map((t,i)=>`<div class="stack-item" data-task-context="${esc(t.id)}"><span class="rank">${i+1}</span><div><div class="item-title">${esc(t.title)}</div><div class="item-meta">${esc(t.project||'Ohne Projekt')} · ${t.minutes||30} Min.</div></div><span class="pill ${esc(t.priority)}">${labelPriority(t.priority)}</span></div>`).join(''):'<div class="empty">Keine weitere Priorität für heute.</div>';const evs=futureEvents().slice(0,3);$('todayEvents').innerHTML=evs.length?evs.map(e=>`<div class="stack-item"><span class="time">${esc(e.time)}</span><div><div class="item-title">${esc(e.title)}</div><div class="item-meta">${e.duration||60} Min.${e.note?' · '+esc(e.note):''}</div></div></div>`).join(''):'<div class="empty">Keine weiteren Termine heute.</div>';$('todayProjects').innerHTML=data.projects.slice(0,4).map(p=>`<div class="project-chip" data-project-context="${esc(p.name)}"><strong>${esc(p.name)}</strong><span>${esc(p.next||'Nächste Aktion fehlt.')}</span></div>`).join('')}
function renderInbox(){$('inboxCount').textContent=data.inbox.length;$('inboxList').innerHTML=data.inbox.length?data.inbox.map(x=>`<div class="inbox-item" data-inbox="${x.id}"><div><div class="item-title">${esc(x.title)}</div><div class="item-meta">${esc(x.note||'Kein Zusatzkontext')} · ${new Date(x.created).toLocaleDateString('de-DE')}</div></div><div class="inbox-actions"><button class="ghost" data-inbox-task="${x.id}">→ Aufgabe</button><button class="icon-btn" data-inbox-delete="${x.id}">×</button></div></div>`).join(''):'<div class="empty">Inbox leer. Gut so.</div>'}
function renderProjects(){$('projectList').innerHTML=data.projects.map(p=>`<article class="project-card ${context?.type==='project'&&context.name===p.name?'active':''}" data-project-context="${esc(p.name)}"><div class="project-top"><div class="item-title">${esc(p.name)}</div><span class="project-state">${esc(p.state||'Aktiv')}</span></div><div class="project-goal">${esc(p.goal||'Projektziel noch nicht hinterlegt.')}</div><div class="project-block"><small>Nächster Meilenstein</small><strong>${esc(p.milestone||'Noch nicht definiert.')}</strong></div><div class="project-block"><small>Nächste Aktion</small><strong>${esc(p.next||'Noch nicht definiert.')}</strong></div><div class="project-actions">${p.url?`<a href="${esc(p.url)}" target="_blank" rel="noopener">Live ↗</a>`:''}${p.repo?`<a href="${esc(p.repo)}" target="_blank" rel="noopener">Repo ↗</a>`:''}</div></article>`).join('')}
function renderTasks(){let list=activeQueue==='done'?data.tasks.filter(t=>t.done):rankedTasks(activeQueue);$('taskList').innerHTML=list.length?list.map(t=>`<div class="task-item ${t.done?'done':''}" data-task-context="${esc(t.id)}"><div class="task-main"><button class="check" data-task-toggle="${esc(t.id)}">${t.done?'✓':''}</button><div><div class="item-title">${esc(t.title)}</div><div class="item-meta">${esc(t.project||'Ohne Projekt')} · ${t.minutes||30} Min. · ${labelPriority(t.priority)}</div>${t.note?`<div class="item-meta">${esc(t.note)}</div>`:''}</div></div><div class="task-actions"><button class="icon-btn" data-task-delete="${esc(t.id)}">×</button></div></div>`).join(''):'<div class="empty">In diesem Bereich ist nichts offen.</div>';document.querySelectorAll('[data-queue]').forEach(b=>b.classList.toggle('active',b.dataset.queue===activeQueue))}
function renderCalendar(){const events=allEvents();$('calendarEvents').innerHTML=events.length?events.map(e=>`<div class="timeline-event"><span class="time">${esc(e.time)}</span><div><div class="item-title">${esc(e.title)}</div><div class="item-meta">${e.duration||60} Min.${e.note?' · '+esc(e.note):''}</div></div><button class="icon-btn" data-event-delete="${esc(e.id)}">×</button></div>`).join(''):'<div class="empty">Keine Termine eingetragen.</div>';const windows=freeWindows();$('freeWindows').innerHTML=windows.length?windows.map(w=>`<div class="free-window"><strong>${w.start}–${w.end}</strong><span>${w.minutes} Minuten frei</span></div>`).join(''):'<div class="empty">Keine längeren freien Fenster mehr.</div>';$('calendarSummary').textContent=`${events.length} Termine · ${windows.reduce((a,b)=>a+b.minutes,0)} Min. frei`}
function freeWindows(){const start=Math.max(nowMinutes(),8*60),end=20*60,events=allEvents().map(e=>({start:timeToMinutes(e.time),end:(timeToMinutes(e.time)||0)+(e.duration||60)})).filter(e=>e.start!==null&&e.end>start&&e.start<end).sort((a,b)=>a.start-b.start);let cursor=start,out=[];for(const e of events){if(e.start>cursor&&e.start-cursor>=20)out.push({start:fmtMin(cursor),end:fmtMin(e.start),minutes:e.start-cursor});cursor=Math.max(cursor,e.end)}if(end-cursor>=20)out.push({start:fmtMin(cursor),end:fmtMin(end),minutes:end-cursor});return out}
const fmtMin=m=>`${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`;
function renderMonitor(){const inbox=data.inbox.length,missingActions=data.projects.filter(p=>!p.next).length,blocked=data.projects.filter(p=>p.blocker&&p.blocker!=='—').length,today=rankedTasks('today').length;const cards=[{title:'Inbox',state:inbox>5?'warn':'good',label:inbox>5?'Aufräumen':'Gut',copy:inbox?`${inbox} ungeklärte Einträge warten auf Entscheidung.`:'Keine offenen Inbox-Einträge.'},{title:'Projekt-Hygiene',state:missingActions?'warn':'good',label:missingActions?'Unvollständig':'Gut',copy:missingActions?`${missingActions} Projekte ohne nächste Aktion.`:'Alle Projekte haben eine nächste Aktion.'},{title:'Blocker',state:blocked>3?'warn':'good',label:blocked>3?'Prüfen':'Dokumentiert',copy:`${blocked} Projekte haben aktuell einen dokumentierten Blocker.`},{title:'Tageslast',state:today>6?'warn':'good',label:today>6?'Zu viel':'Machbar',copy:`${today} Aufgaben sind für heute eingeplant.`},{title:'Dashboard',state:'good',label:'Live',copy:'Personal OS läuft über GitHub Pages. Automatische CI-/Uptime-Prüfung ist noch nicht angebunden.'}];$('monitorList').innerHTML=cards.map(c=>`<div class="monitor-card"><div class="monitor-head"><div class="item-title">${c.title}</div><span class="health ${c.state}">${c.label}</span></div><p>${c.copy}</p></div>`).join('')}
function renderLibrary(){const links=[...data.links,{title:'Dashboard · Live',url:'https://hapo3005.github.io/dash/'},{title:'Dashboard · Repo',url:'https://github.com/hapo3005/dash'}];$('libraryList').innerHTML=links.map(l=>`<div class="library-card"><a href="${esc(l.url)}" target="_blank" rel="noopener"><strong>${esc(l.title)}</strong></a><small>${esc(l.url)}</small></div>`).join('')}
function renderModules(){$('moduleList').innerHTML=[['Gesundheit','Xiaomi-/Health-Daten später als eigenständiges Modul. Auf Heute nur bei echtem Handlungsbedarf.'],['Smart Home','Szenen und Haussteuerung getrennt von der täglichen Arbeitssteuerung.'],['Finanzen','Budgets, Verträge und Abweichungen – nicht als permanente Zahlenwand.'],['Immobilien','Objektsuche, Kalkulationen und Entscheidungen als eigener Workspace.'],['Mobilität','Fahrzeug- und Finanzierungsvergleiche getrennt von Tagesaufgaben.'],['Einkauf','Preisvergleich und Angebotslogik als eigenes Nutzmodul.']].map(([a,b])=>`<div class="module-card"><div class="item-title">${a}</div><p>${b}</p></div>`).join('')}
function renderContext(){const body=$('contextBody');if(!context){body.innerHTML='<div class="context-empty">Wähle ein Projekt oder eine Aufgabe. Hier erscheinen nur die Informationen, die für den aktuellen Kontext relevant sind.</div>';return}if(context.type==='project'){const p=data.projects.find(x=>x.name===context.name);if(!p){context=null;return renderContext()}body.innerHTML=`<h2 class="context-title">${esc(p.name)}</h2><div class="context-sub">${esc(p.state||'Aktiv')} · Projekt</div><div class="context-section"><small>Ziel</small><p>${esc(p.goal||'—')}</p></div><div class="context-section"><small>Nächste Aktion</small><p>${esc(p.next||'—')}</p></div><div class="context-section"><small>Blocker</small><p>${esc(p.blocker||'Kein Blocker hinterlegt.')}</p></div><div class="context-section"><small>Zuletzt</small><p>${esc(p.last||'Keine letzte Aktivität hinterlegt.')}</p></div><div class="context-section context-links">${p.url?`<a href="${esc(p.url)}" target="_blank">Live ↗</a>`:''}${p.repo?`<a href="${esc(p.repo)}" target="_blank">Repo ↗</a>`:''}</div>`}else{const t=data.tasks.find(x=>x.id===context.id);if(!t){context=null;return renderContext()}const p=data.projects.find(x=>x.name===t.project);body.innerHTML=`<h2 class="context-title">${esc(t.title)}</h2><div class="context-sub">${labelPriority(t.priority)} · ${t.minutes||30} Min.</div><div class="context-section"><small>Projekt</small><p>${esc(t.project||'Ohne Projekt')}</p></div><div class="context-section"><small>Kontext</small><p>${esc(t.note||'Kein Zusatzkontext hinterlegt.')}</p></div>${p?`<div class="context-section"><small>Projektziel</small><p>${esc(p.goal||'—')}</p></div><div class="context-section"><small>Projektblocker</small><p>${esc(p.blocker||'—')}</p></div>`:''}`}}
function renderAll(){renderHeader();renderToday();renderInbox();renderProjects();renderTasks();renderCalendar();renderMonitor();renderLibrary();renderModules();renderContext();$('projectOptions').innerHTML='<option value="">Ohne Projekt</option>'+data.projects.map(p=>`<option value="${esc(p.name)}">${esc(p.name)}</option>`).join('')}
async function weather(){try{const city=data.city||'Wittlich',g=await fetch(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(city)}&count=1&language=de&format=json`).then(r=>r.json()),p=g.results?.[0];if(!p)return;const w=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${p.latitude}&longitude=${p.longitude}&current=temperature_2m,weather_code&timezone=auto`).then(r=>r.json());$('weather').textContent=`${Math.round(w.current.temperature_2m)}° · ${p.name}`}catch{$('weather').textContent='Wetter offline'}}
function openTaskDialog(prefill={}){$('taskTitle').value=prefill.title||'';$('taskNote').value=prefill.note||'';$('taskPriority').value=prefill.priority||'medium';$('taskMinutes').value=prefill.minutes||30;$('taskBucket').value=prefill.bucket||'today';$('projectOptions').value=prefill.project||'';$('taskDialog').showModal()}
function selectProject(name){context={type:'project',name};renderProjects();renderContext()}
function selectTask(id){context={type:'task',id};renderContext()}
document.addEventListener('click',e=>{const page=e.target.closest('[data-page]');if(page){showPage(page.dataset.page);return}const project=e.target.closest('[data-project-context]');if(project){selectProject(project.dataset.projectContext);return}const task=e.target.closest('[data-task-context]');if(task&&!e.target.closest('button')){selectTask(task.dataset.taskContext);return}if(e.target.id==='menuBtn'){document.querySelector('.sidebar').classList.toggle('open');return}if(e.target.id==='quickCapture'||e.target.id==='addInbox'){$('captureDialog').showModal();return}if(e.target.id==='addTaskBtn'){openTaskDialog();return}if(e.target.id==='addEventBtn'){$('eventDialog').showModal();return}if(e.target.id==='clearContext'){context=null;renderProjects();renderContext();return}if(e.target.dataset.queue){activeQueue=e.target.dataset.queue;renderTasks();return}if(e.target.dataset.taskToggle){const t=data.tasks.find(x=>x.id===e.target.dataset.taskToggle);if(t){t.done=!t.done;t.bucket=t.done?'done':'today';save();renderAll()}return}if(e.target.dataset.taskDelete){data.tasks=data.tasks.filter(x=>x.id!==e.target.dataset.taskDelete);save();renderAll();return}if(e.target.dataset.eventDelete){data.events=data.events.filter(x=>x.id!==e.target.dataset.eventDelete);save();renderAll();return}if(e.target.dataset.inboxDelete){data.inbox=data.inbox.filter(x=>x.id!==e.target.dataset.inboxDelete);save();renderAll();return}if(e.target.dataset.inboxTask){const x=data.inbox.find(i=>i.id===e.target.dataset.inboxTask);if(x){openTaskDialog({title:x.title,note:x.note});data.inbox=data.inbox.filter(i=>i.id!==x.id);save();renderInbox()}return}if(e.target.id==='startNow'&&currentNowTaskId){selectTask(currentNowTaskId);e.target.textContent='Gestartet';setTimeout(()=>e.target.textContent='Starten',900);return}if(e.target.id==='deferNow'&&currentNowTaskId){const t=data.tasks.find(x=>x.id===currentNowTaskId);if(t){t.bucket='week';save();renderAll()}return}if(e.target.id==='openNowProject'&&currentNowTaskId){const t=data.tasks.find(x=>x.id===currentNowTaskId);if(t?.project){selectProject(t.project);showPage('projects')}return}});
$('captureForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;const title=$('captureTitle').value.trim();if(!title)return;e.preventDefault();data.inbox.unshift({id:uid(),title,note:$('captureNote').value.trim(),created:new Date().toISOString()});save();e.target.reset();$('captureDialog').close();renderAll()});
$('taskForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;const title=$('taskTitle').value.trim();if(!title)return;e.preventDefault();data.tasks.unshift({id:uid(),title,project:$('projectOptions').value,priority:$('taskPriority').value,minutes:Number($('taskMinutes').value)||30,bucket:$('taskBucket').value,note:$('taskNote').value.trim(),done:false,created:new Date().toISOString(),due:todayISO()});save();e.target.reset();$('taskMinutes').value=30;$('taskDialog').close();renderAll()});
$('eventForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;const title=$('eventTitle').value.trim(),time=$('eventTime').value;if(!title||!time)return;e.preventDefault();data.events.push({id:uid(),title,time,duration:Number($('eventDuration').value)||60,note:$('eventNote').value.trim()});save();e.target.reset();$('eventDuration').value=60;$('eventDialog').close();renderAll()});
window.addEventListener('hashchange',()=>showPage((location.hash||'#today').slice(1)));renderAll();showPage((location.hash||'#today').slice(1));weather();setInterval(renderHeader,30000);